// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/WildEgor/gChecker/internal/adapters"
	"github.com/WildEgor/gChecker/internal/config"
	"github.com/WildEgor/gChecker/internal/handlers"
	"github.com/WildEgor/gChecker/internal/router"
	"github.com/WildEgor/gChecker/internal/services"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from server.go:

func NewServer() (*fiber.App, error) {
	appConfig := config.NewAppConfig()
	pingAdapter := adapters.NewPingAdapter(appConfig)
	healthCheckHandler := handlers.NewHealthCheckHandler(pingAdapter)
	routerRouter := router.NewRouter(healthCheckHandler)
	telegramConfig := config.NewTelegramConfig()
	telegramAdapter := adapters.NewTelegramAdapter(telegramConfig)
	healthCheckAdapter, err := adapters.NewHealthCheckAdapter()
	if err != nil {
		return nil, err
	}
	servicesConfig := config.NewServicesConfig()
	checkerService := services.NewCheckerService(telegramAdapter, healthCheckAdapter, servicesConfig)
	app := NewApp(appConfig, routerRouter, checkerService)
	return app, nil
}

// server.go:

var ServerSet = wire.NewSet(AppSet)
