// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pkg

import (
	"github.com/WildEgor/checker/pkg/adapters"
	"github.com/WildEgor/checker/pkg/config"
	"github.com/WildEgor/checker/pkg/handlers"
	"github.com/WildEgor/checker/pkg/router"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
)

// Injectors from server.go:

func New() (*fiber.App, error) {
	appConfig := config.NewAppConfig()
	pingAdapter := adapters.NewPingAdapter(appConfig)
	healthCheckHandler := handlers.NewHealthCheckHandler(pingAdapter)
	routerRouter := router.NewRouter(healthCheckHandler)
	app := NewApp(appConfig, routerRouter)
	return app, nil
}

// server.go:

var Set = wire.NewSet(AppSet)
