// Code generated by Wire. DO NOT EDIT.

package pkg

import (
	"github.com/WildEgor/checker/pkg/config"
	"github.com/WildEgor/checker/pkg/handlers"
	adapters "github.com/WildEgor/checker/pkg/infrastructure/adapters/ping"
	"github.com/gofiber/fiber"
	"github.com/google/wire"
)

func New() (*fiber.App, error) {
	configConfig := config.NewAppConfig()
	statusRepository := adapters.NewPingAdapter(configConfig)
	statusHandler := handlers.NewHealthCheckHandler(statusRepository)
	app := NewApp(statusHandler)
	return app, nil
}

var Set = wire.NewSet(AppSet)
